### ISSUE TITLE
Flink Runtime NoClassDefFoundError

### ISSUE THREAD

**Issue by oyakimets** [ANierbeck/BusFloatingData#9]
Hello guys!

While trying to run the app on lightbend activator 1.3.12 I've  got this error at runtime.

[oleg@fed25 bfd]$ ./bin/activator flinkDigest/run
[info] Loading project definition from /home/oleg/act1312/bfd/project
[info] Set current project to BusFloatingData (in build file:/home/oleg/act1312/bfd/)
[info] Running de.nierbeck.floating.data.stream.flink.KafkaToCassandraFlinkApp 

[error] (run-main-0) java.lang.NoClassDefFoundError: org/apache/flink/streaming/util/serialization/DeserializationSchema
java.lang.NoClassDefFoundError: org/apache/flink/streaming/util/serialization/DeserializationSchema
	at de.nierbeck.floating.data.stream.flink.KafkaToCassandraFlinkApp.main(KafkaToCassandraFlinkApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.streaming.util.serialization.DeserializationSchema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.nierbeck.floating.data.stream.flink.KafkaToCassandraFlinkApp.main(KafkaToCassandraFlinkApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last flinkDigest/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last flinkDigest/compile:run for the full output.
[error] (flinkDigest/compile:run) Nonzero exit code: 1
[error] Total time: 4 s, completed Mar 30, 2017 7:08:44 PM

My environment is Fedora25 on VirtualBox (Windows 10 host)

KindRegards,
Oleg

**Comment by ANierbeck** [comment]
It's a known issue right now. 
As the current flink sub-module right now doesn't compile in the overall build. 

workaround for now: Disable the flink module from the list of sub modules in the build.sbt.

**Comment by ANierbeck** [comment]
Flink is especially nasty right now, as they somehow embedded Guava which is in conflict with the guava provided by the dependency chain on the cassandra driver.

**Comment by ANierbeck** [comment]
at least locally it is working
